### ISSUE TITLE
SAMP api.read_chat is not working in my code

### ISSUE THREAD

**Issue by lakimancic** [rmdlv/python-samp#1]
Hi rmdlv,
First I want to thank you on uploading this library on github, it is very useful for me.
But I have issue with api read_chat method, I'm constantly getting errors:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 112: character maps to <undefined>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 10: invalid start byte
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 230: character maps to <undefined>
I tried some different encodings like utf-8, cp1251 and cp1252, but none of them worked, can you please tell me which encoding I should use or is there any other fix for this problem.
Thanks for your attention. I’m looking forward to your reply.

**Comment by rmdlv** [comment]
Hi, try using latin1

**Comment by lakimancic** [comment]
I tried, latin1 didn't give me errors, but it gave me nonsense like this:
kCIÞÁ?áAIt.{Áx~<ö
                 àzAÜÞzÞ©@&°AI▬ÍÀØÀÀN; I☻AÈ&¶@rµ@àò]?éZ¿2!5@EAIÄg«Â♦ÃÁ|wIÁÜh«B@AÀ¤IA:¶;►µ;]z³BI°×ãÂ£íaÃlhÜÂHXZC▬lÃBt¸æBáØPBÂp%@

**Comment by rmdlv** [comment]
Apparently, the only correct solution would be to use a chatlog file

**Comment by lakimancic** [comment]
chatlog worked, thank you for answering me.
